INSERT INTO [dbo].[Colors](CatColor)
	VALUES
	('Bengal - Marbled'),
	('Bengal - Spotted'),
	('Bengal - Rosetted'),
	('Black'),
	('Black and Brown'),
	('Chimera'),
	('Chocolate'),
	('Chocolate - Patterned'),
	('Cinnamon'),
	('Cinammon - Patterned'),
	('Colourpoint (Himalayan)'),
	('Cream'),
	('Grey - Light'),
	('Grey - Medium'),
	('Grey - Dark'),
	('Mink (Tonkinese)'),
	('Mittens'),
	('Orange'),
	('Orange Spotted'),
	('Orange Swirled'),
	('Ragdoll'),
	('Sepia (Burmese)'),
	('Silver and Golden'),
	('Tabby - Classic (Blotched)'),
	('Tabby - Mackerel'),
	('Tabby - Non-Striped'),
	('Tabby - Other Pattern'),
	('Tabby - Spotted'),
	('Tabby - Ticked'),	
	('Tortoiseshell'),
	('Tri Color'),
	('Tuxedos'),
	('White'),
	('White Spotting - High Grade'),
	('White Spotting - Low Grade'),
	('White Spotting - Medium Grade');

INSERT INTO [dbo].[Breeds](CatBreed)
	VALUES
	('Abyssian Cat'),
	('American Bobtail'),
	('American Curl'),
	('American Shorthair'),
	('American Wirehair'),
	('Balinese-Javanese'),
	('Bengal'),
	('Bombay'),
	('British Shorthair'),
	('Burmese'),
	('Chartreux'),
	('Cornish Rex'),
	('Devon Rex'),
	('Egyptian Mau'),
	('European Burmese'),
	('Himalayan'),
	('Japanese Bobtail'),
	('Korat'),
	('LaPerm'),
	('Maine Coon'),
	('Manx'),
	('Norwegian Forest'),
	('Ocicat'),
	('Oriental'),
	('Persian'),
	('Peterbald'),
	('Pixiebob'),
	('Ragamuffin'),
	('Ragdoll'),
	('Scottish Fold'),
	('Selkirk'),
	('Siamese'),
	('Siberian'),
	('Singapura'),
	('Somali'),
	('Sphynx'),
	('Tabby'),
	('Tonkinese'),
	('Toyger'),
	('Turkish'),
	('Turkish Van Cat'),
	('Unknown');

INSERT INTO [dbo].[Personalities](Type)
	VALUES
	('Active'),
	('Adventurous'),
	('Affectionate'),
	('Agile'),
	('All About Boxes'),
	('Bird Watcher'),
	('Couch Cat'),
	('Cuddly'),
	('Curious'),
	('Dislikes New People'),
	('Dependent'),
	('Dominant'),
	('Enjoys Water'),
	('Fearless'),
	('Friendly'),
	('Funny'),
	('Hates Water'),
	('Hunter'),
	('Hyper'),
	('Independent'),
	('Indoor'),
	('Indoor/Outdoor'),
	('Intelligent'),
	('Lap Cat'),
	('Likes New People'),
	('Loyal'),
	('Outdoor'),
	('Outgoing'),
	('Playful'),
	('Quiet'),
	('Skittish'),
	('Silly'),
	('Sleepy'),
	('Spontaneous'),
	('Stretchy'),
	('Studious'),
	('Timid'),
	('Troublemaker'),
	('Vocal'),
	('Water-obsessed'),
	('Wet Food Obsessed'),
	('Window Cat'),
	('Dry Food Obsessed');	

