INSERT INTO [dbo].[Colors](CatColor)
	VALUES
	('Bengal - Marbled'),
	('Bengal - Spotted'),
	('Bengal - Rosetted'),
	('Black'),
	('Black and Brown'),
	('Chimera'),
	('Chocolate'),
	('Chocolate - Patterned'),
	('Cinnamon'),
	('Cinammon - Patterned'),
	('Colourpoint (Himalayan)'),
	('Cream'),
	('Grey - Light'),
	('Grey - Medium'),
	('Grey - Dark'),
	('Mink (Tonkinese)'),
	('Mittens'),
	('Orange'),
	('Orange Spotted'),
	('Orange Swirled'),
	('Ragdoll'),
	('Sepia (Burmese)'),
	('Silver and Golden'),
	('Tabby - Classic (Blotched)'),
	('Tabby - Mackerel'),
	('Tabby - Non-Striped'),
	('Tabby - Other Pattern'),
	('Tabby - Spotted'),
	('Tabby - Ticked'),	
	('Tortoiseshell'),
	('Tri Color'),
	('Tuxedos'),
	('White'),
	('White Spotting - High Grade'),
	('White Spotting - Low Grade'),
	('White Spotting - Medium Grade');

INSERT INTO [dbo].[Breeds](CatBreed)
	VALUES
	('Abyssian Cat'),
	('American Bobtail'),
	('American Curl'),
	('American Shorthair'),
	('American Wirehair'),
	('Balinese-Javanese'),
	('Bengal'),
	('Bombay'),
	('British Shorthair'),
	('Burmese'),
	('Chartreux'),
	('Cornish Rex'),
	('Devon Rex'),
	('Egyptian Mau'),
	('European Burmese'),
	('Himalayan'),
	('Japanese Bobtail'),
	('Korat'),
	('LaPerm'),
	('Maine Coon'),
	('Manx'),
	('Norwegian Forest'),
	('Ocicat'),
	('Oriental'),
	('Persian'),
	('Peterbald'),
	('Pixiebob'),
	('Ragamuffin'),
	('Ragdoll'),
	('Scottish Fold'),
	('Selkirk'),
	('Siamese'),
	('Siberian'),
	('Singapura'),
	('Somali'),
	('Sphynx'),
	('Tabby'),
	('Tonkinese'),
	('Toyger'),
	('Turkish'),
	('Turkish Van Cat'),
	('Unknown');

INSERT INTO [dbo].[Personalities](Type)
	VALUES
	('Active'),
	('Adventurous'),
	('Affectionate'),
	('Agile'),
	('Cuddly'),
	('Curious'),
	('Dislikes New People'),
	('Dependent'),
	('Dominant'),
	('Friendly'),
	('Funny'),
	('Hunter'),
	('Independent'),
	('Indoor'),
	('Indoor/Outdoor'),
	('Intelligent'),
	('Lap Cat'),
	('Likes New People'),
	('Loyal'),
	('Obsessed with Wet Food'),
	('Only Eats with Dry Food'),
	('Outdoor'),
	('Outgoing'),
	('Playful'),
	('Skittish'),
	('Silly'),
	('Sleepy'),
	('Spontaneous'),
	('Stretchy'),
	('Studious'),
	('Timid'),
	('Vocal'),
	('Water-obsessed');
	

